### ISSUE TITLE
Exception in test code

### ISSUE THREAD

**Issue by velidurmuscan** [milg0/onvif-java-lib#14]
An exception has occured when I tried to run test code below:
```
import java.net.ConnectException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.xml.soap.SOAPException;

import de.onvif.soap.OnvifDevice;

public class OnvifTest {
   public static void main(String[] args) {
      try {
         OnvifDevice nvt = new OnvifDevice("192.168.66.59");
         Date nvtDate = nvt.getDevices().getDate();
         System.out.println(new SimpleDateFormat().format(nvtDate));
      }
      catch (ConnectException e) {
         System.err.println("Could not connect to NVT.");
      }
      catch (SOAPException e) {
         e.printStackTrace();
      }
   }
}
```
My camera does definitely works, because I watched IP stream via VLC player according to datasheet of camera. I think the reason of the problem is related to file tree of my Java project. I searched for solutions on Google a lot. Unfortunately there are not enough solutions working for me and I am a newbie to SOAP. How can I handle this problem? Thanks in advance.
Console output can be seen below:
```
Request SOAP Message (GetCapabilities): <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header/><env:Body><GetCapabilities xmlns="http://www.onvif.org/ver10/device/wsdl"/></env:Body></env:Envelope>
Oca 04, 2018 10:21:42 AM com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection post
SEVERE: SAAJ0008: Bad Response; Method Not Allowed
Unexpected response. Response should be from class class org.onvif.ver10.device.wsdl.GetCapabilitiesResponse, but response is: null
com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (405Method Not Allowed
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.call(Unknown Source)
	at de.onvif.soap.SOAP.createSOAPRequest(SOAP.java:89)
	at de.onvif.soap.devices.InitialDevices.getCapabilities(InitialDevices.java:141)
	at de.onvif.soap.OnvifDevice.init(OnvifDevice.java:148)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:89)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:105)
	at OnvifTest.main(OnvifTest.java:12)
Caused by: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (405Method Not Allowed
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Unknown Source)
	... 7 more

CAUSE:

com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (405Method Not Allowed
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Unknown Source)
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.call(Unknown Source)
	at de.onvif.soap.SOAP.createSOAPRequest(SOAP.java:89)
	at de.onvif.soap.devices.InitialDevices.getCapabilities(InitialDevices.java:141)
	at de.onvif.soap.OnvifDevice.init(OnvifDevice.java:148)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:89)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:105)
	at OnvifTest.main(OnvifTest.java:12)

CAUSE:

com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (405Method Not Allowed
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Unknown Source)
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.call(Unknown Source)
	at de.onvif.soap.SOAP.createSOAPRequest(SOAP.java:89)
	at de.onvif.soap.devices.InitialDevices.getCapabilities(InitialDevices.java:141)
	at de.onvif.soap.OnvifDevice.init(OnvifDevice.java:148)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:89)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:105)
	at OnvifTest.main(OnvifTest.java:12)

```

**Comment by velidurmuscan** [comment]
I solved the problem. There were several reasons which I explained below.
1) While creating new device object, the port has to be referred.
2) While creating new device object, username and password has to be referred.
In my case, the problematic code line is below.
`OnvifDevice nvt = new OnvifDevice("192.168.66.59");`
And the correct code line is below. In this code, _192.168.66.59_ is the static IP adress of my camera, _8080_ is the port which is mentioned in my camera's datasheet, _admin_ and _admin_ are username and password which are mentioned also in my camera's datasheet. Although I intentionally did not set any username and password for my camera and I never logged into camera software with username and password, they has to be referred in the java code.
`OnvifDevice nvt = new OnvifDevice("192.168.66.59:8080", "admin", "admin");`
