### ISSUE TITLE
Bad response Exception

### ISSUE THREAD

**Issue by farzad-kafami** [milg0/onvif-java-lib#9]
I download and run this library but when I type command 'url' or 'profiles' get below exception
`SEVERE: SAAJ0008: Bad Response; Bad Request
Unexpected response. Response should be from class class org.onvif.ver10.media.wsdl.GetProfilesResponse, but response is: null
com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (400Bad Request
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.call(Unknown Source)
	at de.onvif.soap.SOAP.createSOAPRequest(SOAP.java:89)
	at de.onvif.soap.SOAP.createSOAPMediaRequest(SOAP.java:49)
	at de.onvif.soap.devices.InitialDevices.getProfiles(InitialDevices.java:159)
	at de.onvif.Main.main(Main.java:69)
Caused by: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (400Bad Request
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Unknown Source)
	... 5 more

CAUSE:

com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (400Bad Request
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Unknown Source)
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.call(Unknown Source)
	at de.onvif.soap.SOAP.createSOAPRequest(SOAP.java:89)
	at de.onvif.soap.SOAP.createSOAPMediaRequest(SOAP.java:49)
	at de.onvif.soap.devices.InitialDevices.getProfiles(InitialDevices.java:159)
	at de.onvif.Main.main(Main.java:69)

CAUSE:

com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Bad response: (400Bad Request
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.post(Unknown Source)
	at com.sun.xml.internal.messaging.saaj.client.p2p.HttpSOAPConnection.call(Unknown Source)
	at de.onvif.soap.SOAP.createSOAPRequest(SOAP.java:89)
	at de.onvif.soap.SOAP.createSOAPMediaRequest(SOAP.java:49)
	at de.onvif.soap.devices.InitialDevices.getProfiles(InitialDevices.java:159)
	at de.onvif.Main.main(Main.java:69)
Exception in thread "main" java.lang.NullPointerException
	at de.onvif.Main.main(Main.java:70)`

can help me why this exception occures

**Comment by milg0** [comment]
Your network video transmitter doesn't seem to support the simple requests for url or profiles because it delievers no answers for the SOAP requests.

**Comment by farzad-kafami** [comment]
Thanks for the answer
my problem was incorrect password now i connect to camera and get url and profiles without exception
